version: '3'
services: 
  web:
    container_name: node 
    image: docker-node-mongo
    build: .
    command: nodemon --legacy-watch index.js
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    links:
      - "mongo"  
  mongo:
    container_name: mongo 
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"